/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 25 03:54:04 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ItemStock8;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ItemStock8_ESTest extends ItemStock8_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ItemStock8 itemStock8_0 = new ItemStock8();
      int[] intArray0 = new int[3];
      intArray0[1] = 2998;
      int int0 = itemStock8_0.countTotalItem(intArray0);
      assertEquals(2998, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ItemStock8 itemStock8_0 = new ItemStock8();
      // Undeclared exception!
      try { 
        itemStock8_0.countTotalItem((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ItemStock8", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ItemStock8 itemStock8_0 = new ItemStock8();
      int[] intArray0 = new int[0];
      int int0 = itemStock8_0.countTotalItem(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ItemStock8 itemStock8_0 = new ItemStock8();
      int[] intArray0 = new int[10];
      int int0 = itemStock8_0.countTotalItem(intArray0);
      assertEquals(0, int0);
  }
}
