/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 25 03:56:58 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ItemStock10;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ItemStock10_ESTest extends ItemStock10_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int[] intArray0 = new int[4];
      ItemStock10 itemStock10_0 = new ItemStock10();
      int int0 = itemStock10_0.addition(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ItemStock10 itemStock10_0 = new ItemStock10();
      int[] intArray0 = new int[1];
      intArray0[0] = 680;
      int int0 = itemStock10_0.addition(intArray0);
      assertEquals(680, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ItemStock10 itemStock10_0 = new ItemStock10();
      // Undeclared exception!
      try { 
        itemStock10_0.addition((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ItemStock10", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[0];
      ItemStock10 itemStock10_0 = new ItemStock10();
      int int0 = itemStock10_0.addition(intArray0);
      assertEquals((-1), int0);
  }
}
