/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 25 03:49:13 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ItemStock1;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ItemStock1_ESTest extends ItemStock1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ItemStock1 itemStock1_0 = new ItemStock1();
      int[] intArray0 = new int[1];
      intArray0[0] = 496;
      int int0 = itemStock1_0.addition1(intArray0);
      assertEquals(496, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ItemStock1 itemStock1_0 = new ItemStock1();
      // Undeclared exception!
      try { 
        itemStock1_0.addition1((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ItemStock1", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[0];
      ItemStock1 itemStock1_0 = new ItemStock1();
      int int0 = itemStock1_0.addition1(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ItemStock1 itemStock1_0 = new ItemStock1();
      int[] intArray0 = new int[10];
      int int0 = itemStock1_0.addition1(intArray0);
      assertEquals(0, int0);
  }
}
