/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 25 03:50:47 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ItemStock3;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ItemStock3_ESTest extends ItemStock3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ItemStock3 itemStock3_0 = new ItemStock3();
      int[] intArray0 = new int[1];
      intArray0[0] = 2629;
      int int0 = itemStock3_0.addition3(intArray0);
      assertEquals(2629, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ItemStock3 itemStock3_0 = new ItemStock3();
      // Undeclared exception!
      try { 
        itemStock3_0.addition3((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ItemStock3", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ItemStock3 itemStock3_0 = new ItemStock3();
      int[] intArray0 = new int[0];
      int int0 = itemStock3_0.addition3(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ItemStock3 itemStock3_0 = new ItemStock3();
      int[] intArray0 = new int[2];
      int int0 = itemStock3_0.addition3(intArray0);
      assertEquals(0, int0);
  }
}
