/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 25 03:51:39 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ItemStock4;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ItemStock4_ESTest extends ItemStock4_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ItemStock4 itemStock4_0 = new ItemStock4();
      int[] intArray0 = new int[2];
      int int0 = itemStock4_0.add(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ItemStock4 itemStock4_0 = new ItemStock4();
      int[] intArray0 = new int[1];
      intArray0[0] = 853;
      int int0 = itemStock4_0.add(intArray0);
      assertEquals(853, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ItemStock4 itemStock4_0 = new ItemStock4();
      // Undeclared exception!
      try { 
        itemStock4_0.add((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ItemStock4", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[0];
      ItemStock4 itemStock4_0 = new ItemStock4();
      int int0 = itemStock4_0.add(intArray0);
      assertEquals((-1), int0);
  }
}
