/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 25 03:54:12 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ItemStock9;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ItemStock9_ESTest extends ItemStock9_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ItemStock9 itemStock9_0 = new ItemStock9();
      int[] intArray0 = new int[2];
      intArray0[0] = 612;
      int int0 = itemStock9_0.countItemPrice(intArray0);
      assertEquals(612, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ItemStock9 itemStock9_0 = new ItemStock9();
      // Undeclared exception!
      try { 
        itemStock9_0.countItemPrice((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.ItemStock9", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[0];
      ItemStock9 itemStock9_0 = new ItemStock9();
      int int0 = itemStock9_0.countItemPrice(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ItemStock9 itemStock9_0 = new ItemStock9();
      int[] intArray0 = new int[3];
      int int0 = itemStock9_0.countItemPrice(intArray0);
      assertEquals(0, int0);
  }
}
